name: Testing

on:
  push:

jobs:
  build-linux:
    name: Test libs    
    runs-on: macos-latest

    steps:
      - name: Clone whisper.unity
        uses: actions/checkout@v3

      - name: whisper.unity libs
        run: |
          f=libllamalib_ios-arm64.a
          nm -gU $f > $f.symbols
          curr_dir=`pwd`
          cd Packages/com.whisper.unity/Plugins/iOS
          for f in *.a;do
            echo $f
            nm -gU $f > $f.symbols
          done
          mv *.symbols $curr_dir
          cd $curr_dir
          zip symbols.zip *.symbols

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: symbols
          path: symbols.zip
          if-no-files-found: error